テーブル作成SQL#10
sumstockccg/lamp_practice pull request #11
Opened 2021-07-07 05:29 UTC by NatsumiFuruya

課題２の課題1・追加テーブルの設計を行っています。
追加テーブル用のSQLを「append_schema.sql」に書きました。
確認お願いします。

2021-07-07 06:10 UTC, kamezaki01 requested changes

2021-07-07 06:10 UTC, kamezaki01 commented on lamp_dock/append_schema.sql
> +  order_id INT AUTO_INCREMENT,
purchaseテーブルのidなので、命名するとしたらpurchase_idが自然かと思います。
また、このようなidは単純に「id」と命名されることが多いです。

2021-07-07 06:10 UTC, kamezaki01 commented on lamp_dock/append_schema.sql
> +  order_id INT,
こちらも合わせて修正しましょう。
よくあるやり方としては、purchaseテーブルのidを「id」と定義し、こちらのカラムは「purchase_id」と定義します。（[テーブル名]_idという命名）

2021-07-07 06:10 UTC, kamezaki01 commented on lamp_dock/append_schema.sql
> +CREATE TABLE order(
テーブル名を見ると、purchaseとorderの違いが少しわかりにくいです。
私の場合、purchase→orders、order→order_itemsなどと命名します。
修正はしなくても大丈夫です！

2021-07-07 06:10 UTC, kamezaki01 commented on lamp_dock/append_schema.sql
> +);
ECサイトでは、運用中に商品の名前や値段が変わる可能性があります。
なので購入時のものをとっておきましょう！

2021-07-07 09:56 UTC, NatsumiFuruya commented on lamp_dock/append_schema.sql
> +  order_id INT AUTO_INCREMENT,
承知しました。テーブル名を「orders」に、カラム名を「id」と変更します。

2021-07-07 10:00 UTC, NatsumiFuruya commented on lamp_dock/append_schema.sql
> +  order_id INT,
「purchase」テーブルを「orders」に変更するのでカラム名を、「order_id」→「orders_id」と変更します。

2021-07-07 10:01 UTC, NatsumiFuruya commented on lamp_dock/append_schema.sql
> +CREATE TABLE order(
せっかくなので、アドバイスどおり各テーブル名を「purchase」→「orders」、「order」→「order_items」へ変更します。

2021-07-07 10:03 UTC, NatsumiFuruya commented on lamp_dock/append_schema.sql
> +);
言われてみればそうですね！
この場合、購入時の商品名や値段のカラムを追加すればよろしいでしょうか？

2021-07-07 10:11 UTC, kamezaki01 commented on lamp_dock/append_schema.sql
> +);
はい、新たにitem_nameやitem_priceと定義すると良いと思います！

2021-07-08 02:30 UTC, kamezaki01 approved these changes
OKです！

ちなみに伝え忘れていたのですが、命名規則は以下のようになっていることが多いです。
https://qiita.com/genzouw/items/35022fa96c120e67c637
これに則ると、「orders_id」は「order_id」とするほうがわかりやすいかもしれません。
あくまで「こういうやり方もあります」という紹介なので、修正は不要です！

2021-07-08 02:31 UTC, merged